<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="mahen-PC" ignored="0" name="Test" tests="6" failures="1" timestamp="16 Jun 2017 17:13:23 GMT" time="15.165" errors="0">
  <testcase name="fail" time="0.028" classname="com.testng.RetryTestng">
    <skipped/>
  </testcase> <!-- fail -->
  <testcase name="fail" time="0.01" classname="com.testng.RetryTestng">
    <skipped/>
  </testcase> <!-- fail -->
  <testcase name="fail" time="0.003" classname="com.testng.RetryTestng">
    <skipped/>
  </testcase> <!-- fail -->
  <testcase name="fail" time="0.003" classname="com.testng.RetryTestng">
    <skipped/>
  </testcase> <!-- fail -->
  <testcase name="fail" time="0.003" classname="com.testng.RetryTestng">
    <skipped/>
  </testcase> <!-- fail -->
  <testcase name="fail" time="0.007" classname="com.testng.RetryTestng">
    <failure type="java.lang.AssertionError" message="expected [test2] but found [test1]">
      <![CDATA[java.lang.AssertionError: expected [test2] but found [test1]
	at com.testng.RetryTestng.fail(RetryTestng.java:13)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- fail -->
</testsuite> <!-- Test -->
